-- Supabase migration: members and bookings
-- Compatible with the existing app field names used by frontend/backends.

CREATE TABLE IF NOT EXISTS bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id bigint,
  customer_name text NOT NULL,
  email text NOT NULL,
  phone text,
  move_in_date date,
  message text,
  status text DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  password text NOT NULL,
  status text DEFAULT 'active',
  created_at timestamptz DEFAULT now(),
  booked_room bigint,
  username text,
  registration_date timestamptz DEFAULT now(),
  created_by_admin boolean DEFAULT false,
  role text DEFAULT 'user'
);

CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_members_email ON members(email);
